# Config Server accounts.yml - All configuration managed centrally
build:
  version: "3.0"

server:
  port: 8080


# Database configuration
spring:
  datasource:
    url: jdbc:mysql://accountsdb:3306/accountsdb
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  
  # Jackson configuration
  jackson:
    default-property-inclusion: NON_NULL

# Message queue configuration
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# Service discovery configuration
eureka:
  instance:
    prefer-ip-address: true
    hostname: accounts
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 30

# Management and monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

# Business configuration
accounts:
  message: "Welcome to EazyBank accounts related default Docker APIs"
  max-transaction-limit: 50000
  allowed-currencies: "USD,EUR,GBP"
  feature-flags:
    mobile-payments-enabled: true
    international-transfers: false
  contactDetails:
    name: "John Doe - Developer" 
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

# Logging configuration
logging:
  level:
    com.eazybytes.accounts: DEBUG
    com.eazybank: INFO
    com.netflix.eureka: WARN
    org.springframework.web: WARN
    root: INFO

info:
  app:
    name: "accounts"
    description: "EazyBank Accounts Application Default"
    version: "@project.version@"
