server:
  port: 8080
spring:
  application:
    name: accounts
  config:
    import: configserver:http://configserver:8071/
  datasource:
    url: jdbc:mysql://accountsdb:3306/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  profiles:
    active: "default"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

info:
  app:
    name: "accounts"
    description: "EazyBank Accounts Application"
    version: "1.0.0"
