server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:accountsdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Maintenance mode property for Docker
app:
  maintenance: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application - Docker"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        accounts: DEBUG
