server:
  port: 8072

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true       # Enable automatic route creation from Eureka services
          lower-case-service-id: true
#
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://eurekaserver:8761/eureka/"
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true  # ADD THIS LINE - Critical for gateway actuator endpoints
    health:
      show-details: always
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com.eazybytes.gatewayserver: DEBUG
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        registerHealthIndicator: true
        eventConsumerBufferSize: 10

# CE CONFIGURARE DE KKT