server:
  port: 8072

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      discovery:
        locator:
          enabled: true       # Enable automatic route creation from Eureka services
          lower-case-service-id: true
  # Uncomment when Redis is available
  # data:
  #   redis:
  #     host: redis
  #     port: 6379
  #     connect-timeout: 1000ms
  #     timeout: 10s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://eurekaserver:8761/eureka/"
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted  # CHANGED: Replacement for 'enabled: true'
    health:
      show-details: always
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "EazyBank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com.eazybytes.gatewayserver: DEBUG
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
    #If you don't define any instance, the will be created internally but not shown to the actuator(Lazy Loading)
    instances:
      accountsCircuitBreaker:
        baseConfig: default
      loansCircuitBreaker:
        baseConfig: default
      cardsCircuitBreaker:
        baseConfig: default