# Config Server accounts.yml - All configuration managed centrally
build:
  version: "3.0"

server:
  port: 8090
# Database configuration
spring:
  datasource:
    url: jdbc:mysql://loansdb:3306/loansdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 900000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: embedded  # Changed from 'always' to 'embedded'
      continue-on-error: true

  # Jackson configuration
  jackson:
    default-property-inclusion: NON_NULL

# Message queue configuration
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# Service discovery configuration
eureka:
  instance:
    prefer-ip-address: true
    hostname: loans
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 30

# Management and monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

# Business configuration
loans:
  message: "Welcome to EazyBank loans related default APIs"
  max-transaction-limit: 50000
  allowed-currencies: "USD,EUR,GBP"
  feature-flags:
    mobile-payments-enabled: true
    international-transfers: false
  contactDetails:
    name: "John Doe - Developer" 
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

# Logging configuration
logging:
  level:
    com.eazybytes.loans: DEBUG
    org.springframework.web: DEBUG  # This will help see the header
    org.springframework.boot.autoconfigure.sql.init: DEBUG

# External service URLs (container networking)
external-apis:
  fraud-detection:
    url: http://fraud-service:8080
    timeout: 5000
  notification-service:
    url: http://notification-service:8080
    timeout: 3000

# Static application metadata
info:
  app:
    name: loans
    description: EazyBank Loans Application default
    version: "@project.version@"
